<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>promise</title>
</head>

<body>

</body>

</html>
<script src="./jquery-3.3.1.js"></script>
<script>
    // $.ajax({
    //     url:'./data.json',
    //     success:function(data){
    //         $.ajax({
    //             url:'./data.json',
    //             success:function(){

    //             }
    //         })
    //     }
    // })

    //executor
    // let p = new Promise(function (resolve, reject) {
    //     //代表未来某个将要发生的事件（通常是一个异步操作）
    //     //resolve:执行成功对应的函数
    //     //reject:执行失败对应的函数
    //     //具体时间执行成功还是失败是由 抒写 executor 函数的这个人决定的
    //     // promise实例有三个状态：分别是： //pending:promise当前处于等待状态 初始化状态
    //     //resolved:走了成功的回调函数
    //     //rejected:走了失败的回调函数
    //     //状态一经修改，就不会再发生任何改变
    //     setTimeout(() => {
    //         reject(123)
    //         //resolve(123)
    //     }, 3000);
    // });
    // // console.log(p)
    // //then接收两个函数作为参数，第一个函数对应resolve，第二个函数对应reject、
    // p.then(function (data) {
    //     
    //     console.log('success')
    //     console.log(data)
    // }, function (err) {
    //     console.log('error')
    //     console.log(err)
    //     console.log(aaa)
    // }).then(function (data2) {
    //     console.log('data2', data2)
    // }, function (err2) {
    //     console.log('err2', err2)
    // });
/*----------------------------------------------------------------------*/
    // let p = new Promise(function(res,rej){
    //     $.ajax({
    //         url:'./data.json',
    //         success:res,
    //         error:rej
    //         // error:rej
    //     })
    // })
    // p.then(function(data){
    //     //可以写两个参数 也可以只写一个参数：
    //     //一个参数:对应的成功的回调，失败信息可以通过catch捕获
    //     console.log(data);
    //     return new Promise(function(res,rej){
    //         res(666)
    //     })
    // }).then(function(data2){
    //     console.log(data2)
    // }).catch(function(err){
    //     console.log(err)
    // })
/*----------------------------------------------------------------------*/
new Promise(function(res,rej){
res(123);
console.log(666)
}).then(function(data2){
    console.log(data2)
}).catch(function(err){
    console.log(err)
}).finally(()=>{
    console.log()
})
console.log(999)













</script>